thesofproject/sof-docs

- howtos/process/docbuild.rst
This additional step is necessary until next is merged back to master.
> doc: build howto temporarily points to next in sof

- static/sof-custom.css
Uncomment the CSS style to show a "under development"
message under the breadcrumb trail at the top of the page
Signed-off-by: David B. Kinder <david.b.kinder@intel.com>
> doc: add under development header to pages

- developer_guides/unit_tests.rst
Added guide for symbol wraping in unit tests.
Signed-off-by: Jakub Dabek <jakub.dabek@linux.intel.com>
> doc: add wraping for unit tests

- getting_started/effects/how-to-use-sof-eqctl-tool.rst
- getting_started/index.rst
This patch adds basic usage of the new tool to set up
equalizers during runtime.
Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>
> Add sof-eqctl getting started instructions

- developer_guides/unit_tests.rst
- getting_started/build-guide/build-from-scratch.rst
> build: update listings to use smp

- getting_started/build-guide/build-from-scratch.rst
While following this article I had to change these values to be able to build sof for apl. I guess that makes sense because you have no broxton in xtensa-root and toolchain so it cannot get headers + cannot find binary for *bxt-gcc, because we prepared them for apl in earlier step.
> build: from scratch: fix apollolake config

- getting_started/build-guide/build-from-scratch.rst
This is required changed after soft was depreciated.
One small concern and need your feedback is
1. kvm libvirt-bin packages are not available in Ubuntu 18.04 and 18.10. I assume these are available some old version of Ubuntu. So I didn't remove them.
2. I couldn't find below path after building alsa-lib. So I deleted this line. May old alsa-lib create libaries to that path? I saw one of makefile has /usr/lib/alsa-lib path but any of alsa folder is not created.
$ sudo cp /usr/lib/alsa_lib/*    /usr/lib/x86_64-linux-gnu/alsa-lib
3. I had hard time to build alsa-utils. gitcompile didn't work for me. Not sure why that happened to me. I have good solution but I just put short comments only.
> build from scratch update

- getting_started/setup/setup_up_2_board.rst
delete wrong reference defconfig, added kconfig project link. And how to use Kconfig project for up2 build.
> Updated where to get kconfig for UP2

- howtos/process/docbuild.rst
In order to properly render timing & Gantt diagrams that are going to be
added in upcoming PRs the plantuml.jar version needs to be updated. Expanded
troubleshooting section of installation document to cover detection of
plantuml.jar version misalignment.
> Plantuml.jar updated to version 1.2019.00

- developer_guides/topology/topology.rst
Add debug guidance to topology documentation.
Signed-off-by: Jaska Uimonen <jaska.uimonen@intel.com>
> developer_guides:topology: add debug guidance

- .travis.yml
Use Python 3.6 to build the html
Build sof doc with doxygen
Logs can be found here https://travis-ci.org/xiulipan/sof-docs
TODO: how to deploy the static html to https://github.com/thesofproject/thesofproject.github.io
Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>
> CI: enable travis CI for sof-docs

- howtos/process/docbuild.rst
The troubleshooting section was updated with info on how to deactivate
virtual Python environment used for documentation creation. Paragraphs
were formatted to have number of chars in line not exceeding preffered
line length.
> Add info on deactivation of Python virtual environment

- getting_started/setup/setup_up_2_board.rst
Started out correcting a parsing error (line 112 of setup_up_2_board.rst) and went ahead and switched from quotes to inline code block.
> Small fix to up 2 board setup

- getting_started/build-guide/build-from-scratch.rst
Initial support to build firmware for i.MX8 platforms is already
available in crosstool-ng and newlib-xtensa.
> getting_started: Add build documenation for i.MX8

- getting_started/build-guide/build-from-scratch.rst
FFT library is required to enable alsabat's frequency analysis. This is
optional, Instead of putting this in top build dependency, fftw3 is added
as one optional step before building alsa-utils.
Signed-off-by: Fred Oh <fred.oh@linux.intel.com>
> add to install fftw3 library before alsa-utils

- getting_started/build-guide/build-3rd-party-toolchain.rst
The chapter outlines 3rd party toolchains definition and
adds to the list information on Cadence Tensilica Xtensa (XCC)
compiler including snippet for conditional compilation.
> Add 3rd party toolchains section to getting started guide

- .travis.yml
Commits to publish branch will now result in deploying of static HTML to thesofproject.github.io.
This simplifies the publish process removing the need to build it locally and use the "make publish" command.
The manual process can still be used when/if needed.
> Add "pages" deploy from publish branch

- platforms/intel-legacy/broadwell/index.rst
Because of kernel bug 204237 (and downstream Fedora bug 1750194), we know about more devices which use this platform.
> platforms: Update info for Broadwell

- index.rst
> doc: removed "How-tos" title frm Index since section is gone.

- developer_guides/firmware/kd_integration/images/kd-component-diagram.pu
- developer_guides/firmware/kd_integration/images/kd-e2e-sequence-diagram.pu
- developer_guides/firmware/kd_integration/images/kd-timing-diagram.pu
The diagrams have fixed maximum width to make them fit reading pane on low
resolution monitors.
> Scale down diagrams for Keyword Detection feature

- api/index.rst
- api/pm-runtime-api.rst
Documentation for pm-runtime API should be included.
> api: add reference to pm-runtime dox

- index.rst
- maintainers/admin.rst
- maintainers/code_owners.rst
- maintainers/index.rst
- maintainers/merge_rights.rst
- tsc/index.rst
- tsc/meetings.rst
- tsc/representatives.rst
document who's who in the SOF project
This is a first pass for review, feedback welcome
> sof-docs: Add TSC and maintainers documentation

- contribute/process/docbuild.rst
Build documentation chapter is updated with information about auxiliary
tools their configuration required to generate documentation on Windows.
> Add instruction on documentation generation on Windows

- developer_guides/firmware/index.rst
- developer_guides/firmware/pm-runtime/images/pm-dsp-core-idle.pu
- developer_guides/firmware/pm-runtime/images/pm-dsp-core-init.pu
- developer_guides/firmware/pm-runtime/index.rst
- developer_guides/firmware/pm-runtime/intel/images/dsp-core-lps-cavs-d0-d0i3-d0.pu
- developer_guides/firmware/pm-runtime/intel/pm-dsp-core-cavs.rst
- developer_guides/firmware/pm-runtime/pm-dsp-core.rst
There are two parts: generic one, applicable for any platform
and another detailed one that documents cAVS advanced power
management of DSP core in deeper power states (D0i3).
> pm-runtime: add basic documentation of pm transitions

- getting_started/build-guide/build-from-scratch.rst
i.MX8X is similar with i.MX8. Both use the same compiler
toolchain. They have different defconfig files:
* imx8_defconfig for i.MX8
* imx8x_defconfig for i.MX8X
> getting_started: Add build documentation for i.MX8X

- platforms/index.rst
Add a table listing SOF's supported platforms alongside details of the
minimum HW requirements to run SOF.
Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
> platform: Add data on supported platforms and min requirements.

- algos/index.rst
This patch adds acoustical echo cancellation and multi-microphone
beamformer components. The added Milestone column is populated with
the known SOF releases. The existing descriptions were not edited
otherwise.
Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>
> Algorithms: Add Milestone column and two new planned components

- platforms/intel-cavs/images/cavs-platform-deps.pu
- platforms/intel-cavs/index.rst
- platforms/intel-cavs/tigerlake/images/tgl-memory.dot
- platforms/intel-cavs/tigerlake/index.rst
- platforms/intel-cavs/tigerlake/tgl-config.rst
- platforms/intel-cavs/tigerlake/tgl-memory.rst
The change adds high level description of Tigerlake hw (cavs 2.5).
Specifically support for L1 ROM and L1 data / instruction SRAM
are new in comparison to Cannonlake (cavs 1.8).
> platforms: add description of Tigerlake platform

- platforms/intel-cavs/icelake/icl-config.rst
- platforms/intel-cavs/icelake/icl-memory.rst
- platforms/intel-cavs/icelake/index.rst
The change clarifies that memory map used by Icelake platform
is the same as on Cannonlake. The SSP DAI number is updated.
> platforms: update Icelake configuration details

- platforms/intel-cavs/cannonlake/cnl-memory.rst
- platforms/intel-cavs/tigerlake/tgl-memory.rst
The memory maps for cavs 1.8/2.5 have to reflect both hw capabilities (like
support for large virtual memory space that can be mapped to HPSRAM of a
limited size) and current fw configuration. HW does not support address
virtualization for LPSRAM. Number of physical HPSRAM banks for Cannonlake
was updated.
> platforms: clarify HP/LP SRAM access modes

- developer_guides/firmware/kd_integration/images/kd-state-diagram.pu
- developer_guides/firmware/kd_integration/kd-integration.rst
This adds a state diagram for keyphrase buffer manager.
Signed-off-by: Marcin Rajwa <marcin.rajwa@linux.intel.com>
> kd-integration: add state diagram of keyphrase buffer manager

- developer_guides/introduction.rst
This patch fixes different misspellings i found when reading through
introduction page of developer guides section.
Signed-off-by: Mohana Datta Yelugoti <ymdatta.work@gmail.com>
> developer_guides: introduction: fix misspellings

- developer_guides/firmware/kd_integration/images/kd-timing-diagram.pu
- developer_guides/firmware/kd_integration/kd-integration.rst
An explanation of various types of latencies that determine minimum size of
a keyphrase buffer is added. It includes information about differences in
movement between write and read pointers to the buffer.
> keyword detection: explain formula for keyphrase buffer size

- getting_started/build-guide/build-from-scratch.rst
After change readme align with file names in kconfig repo.
> getting_started: replace sof-mach-driver-defconfig to mach-driver-defconfig

- api/index.rst
- api/uuid-api.rst
- developer_guides/firmware/components/component-overview.rst
- developer_guides/firmware/components/images/comp-driver.pu
Recently added UUIDs requires detailed documentation to
make sure the component developers know how to generate
and use them.
> comp: add uuid documentation and examples

- Makefile
- contribute/process/docbuild.rst
- scripts/requirements.txt
See commit messages for details.
Biggest change is merge Windows and Linux commands into one.
> simplify docbuild: merge Windows and Linux commands. Other minor fixes.

- conf.py
Cpp domain provides much better formatting in Sphinx.
Initialized enum items are correctly displayed, pointer
to functions typedef-ed in place also works fine.
Other projects also tend to use cpp domain for import
from C headers.
> conf: switch breathe to import into cpp domain

- getting_started/build-guide/build-from-scratch.rst
All support is already in place so add instructions for completeness.
Signed-off-by: Yong Zhi <yong.zhi@intel.com>
> getting_started: Add build documenation for ICL and JSL+

- Makefile
Doxygen is not incremental but it is super fast in this project with
this configuration, so run it every time before we run sphinx. Totally
negligible compared to the minutes required by plantUML.jar.
Keep it optional not to add new dependencies. Now for users who opt-in,
this commit will keep showing the doxygen warnings on every incremental
build (unlike the .rst warnings unfortunately).
Print the magic cmake invocation so no one has to go and read the build
HOWTO to get (re)started.
> Makefile: add ../sof/doc/doxygen/ dependency

- substitutions.txt
Fixes commit f4ada42ce36c ("getting_started: Add build documenation for
ICL and JSL+") that added four "WARNING: Undefined substitution
referenced: JSL" and for literal "|JSL|" instances on
https://thesofproject.github.io/latest/getting_started/build-guide/build-from-scratch.html,
example:
>  Current target Intel platforms include: Bay Trail, Cherry Trail,
>  Haswell, Broadwell, Apollo Lake, Cannon Lake, Ice Lake and |JSL|.
> substitutions.txt: add missing |JSL|

- .travis.yml
Since commit a97756ab4307 was merged, Travis shows the following harmless but
misleading message:
```
```
Example: https://travis-ci.org/github/thesofproject/sof-docs/builds/670800271
That's because the sof-docs documentation and sof-docs/Makefile now
expect a sof/doc/ninja.build. So switch sof-docs/.travis.yml away from
Make and to ninja.
In the future we'll probably want cmake -S sof/doc to use a separate
-B build directory. One thing at a time.
> Travis: switch sof/doc sub-build to Ninja

- conf.py
- getting_started/build-guide/build-from-scratch.rst
Start small with build scripts/ and ALSA repos, can easily be expanded
later if everything goes well.
> build-from-scratch: add HTML links to source code thanks to extlinks

- .gitignore
- make.bat
- scripts/requirements.txt
- setup.py
- tox.ini
> Items created/updated to correct tech writer's build

- contribute/linux/development_tree.rst
A limited number of infrastructure changes that will never be merged
upstream is OK.
Based on Pierre's comments deep down (unrelated) https://github.com/thesofproject/linux/pull/1988#discussion_r405047481
> contribute/linux: minor sof-dev-rebase clarifications

- developer_guides/firmware/component-tutorial/tut-i-basic-fw-code.rst
Tutorial source code rebased with the lastest version of APIs.
> comp: tutorial: update part I

- algos/demux/demux.rst
```diff
-.. code-block:: m4
+.. code-block::
```
... to get rid of the following warning:
```
sof-docs/algos/demux/demux.rst:121:
WARNING: Pygments lexer name 'm4' is not known
```
I looked at https://pygments.org/docs/lexers and tried a couple of
alternatives. They all either:
- fail to parse m4's unique `string' syntax and render ugly, or
- are too simplistic and render everything the same except comments;
until the doc changes and then they break mysteriously.
Keep it simple.
Fixes: 6af9f4448b7d5 ("add mux/demux documentation")
> demux: there's no "m4" Python syntax highlighter

- algos/demux/demux.rst
- contribute/process/docbuild.rst
- scripts/requirements-lax.txt
- scripts/requirements.txt
Avoids hardcoding and virtualenvs.
See problem statement and discussion in PR #198 and extensive comments
in the new file itself.
Successfully tested with stock, "apt" versions on Ubuntu 18.04 LTS and
a totally empty 'pip3 list --local'
> New scripts/requirements-lax.txt with '>=' instead of '=='

- Makefile
We just got rid of all sphinx warnings, so let's try to keep it that
way.
Also remove $(Q) to stop hiding the main, longest running and most
important command in the Makefile.
> Makefile: sphinx-build -W --keep-going

- api/dma-drivers-api.rst
sof commit bf6d97c76a5a / https://github.com/thesofproject/sof/pull/2773 moved dma_copy() to a different subgroup to
solve the name clash with struct dma_copy{} which made the function
temporarily disappear from sphinx' output.
> api: add new sof_dma_copy_func subgroup to add dma_copy() func back

- developer_guides/firmware/component-tutorial/tut-i-basic-fw-code.rst
I tested most sphinx versions between 2.0.0 (when cpp:struct: was
introduced) and version 2.3.1 and `cpp:struct:` crashes them all with
the same traceback below. I don't know why but considering 2.4.0 was
released only in late 2019, let's just avoid the issue and use the older
`cpp:class:` instead. This also avoids bumping the sphinx version
in scripts/requirements.
For information I used doxygen version 1.8.15 and my generated file
`doc/doxygen/xml/structcomp__copy__limits.xml` has this line near the top:
`<compounddef id="structcomp__copy__limits" kind="struct" language="C++"
prot="public">`
The world "class" is nowhere in that generated file.
Fixes: e609daf988e2 ("comp: tutorial: update part I)
References:
http://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#cross-ref …
> comp: tutorial: replace cpp:struct: with cpp:class:

- getting_started/build-guide/build-with-docker.rst
The -l option has been removed from the script for over a year since
https://github.com/thesofproject/sof/commit/9840ecbbfe41ce0cc53b5d0215c64c9f87557d39
Signed-off-by: Shreeya Patel <shreeya.patel23498@gmail.com>
> build-with-docker: Remove -l option from xtensa-build-all command

- getting_started/build-guide/build-from-scratch.rst
- getting_started/build-guide/build-with-docker.rst
Currently, if one wishes to follow the documentation but has a different
directory organization for their code they have to replace all the
occurences of ~/work/sof in the documentation with their directory. By
using $SOF_WORKSPACE the user can set the root once and copy paste all
the commands from the documentation as is.
Signed-off-by: Shreeya Patel <shreeya.patel23498@gmail.com>
> build-guide: Use env var for referring ~/work/sof

- developer_guides/linux_driver/index.rst
- developer_guides/linux_driver/third_party/index.rst
- developer_guides/linux_driver/third_party/keyword_detect/keyword_detect.rst
Add Keyword Detection driver implementation and user guide to the third
party features user guide of the SOF linux driver documentation.
Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>
> developers_guides: add user guide for keyword detection

- contribute/process/docbuild.rst
The current github repository link is incorrect, update the file
to point to correct repository.
Signed-off-by: Mohana Datta Yelugoti <ymdatta.work@gmail.com>
> contribute: docbuild: Update the links to repositories

- developer_guides/firmware/component-tutorial/tut-i-basic-fw-code.rst
- developer_guides/firmware/components/component-overview.rst
In new version, each component should have runtime accessible
UUID value, to allow topology build by uuid value instead of
component type.
related with https://github.com/thesofproject/sof/pull/3010
> comp: uuid: Update UUID to runtime version for components

- release.rst
Remove obsolete reference to v1.3 as the latest release. It's better
not to mention the latest here at all and instead just point readers
to the GitHub release page.
Also remove text referring to linux-firmware.git and instead
refer to sof-bin repository as the official channel for binary
release packages.
> release: update release information

- developer_guides/firmware/components/component-overview.rst
- developer_guides/index.rst
- developer_guides/uuid/index.rst
Add a page to describe how to use UUID on SOF, the UUID will be the replacement of the traditional component type.
> UUID usage on SOF

- contribute/index.rst
- contribute/linux/development_tree.rst
- contribute/process/abiprocess.rst
- contribute/process/images/abiprocess.pu
This is documenting the proposed new, refined ABI process as discussed here:
https://github.com/orgs/thesofproject/teams/sof-developers/discussions/35
Document revised process for ABI changes including a new step
for Request-for-Comments phase. This is intended to ensure
early engagement of interface changes across driver and firmware
teams, to avoid wasting effort when concerns are raised at
the very end of the process.
Add cross-links between kernel driver and firmware sections.
> contributing: Add section on process for SOF FW ABI changes

- developer_guides/debugability/logger/index.rst
After removing timestamps it is possible to compare output logs
with tools like diff or similar. Moreover then output logs are
in more compact form.
Related with https://github.com/thesofproject/sof/pull/3087
> logger: Update help message with -h flag

- static/sof-custom.css
Adjust the CSS rules to not hide API group documentation such
as the text we have in include/ipc/header.h. In Breathe output
for doxygen groups, <dt> tags are used to show the group name.
These do not look nice and do not relay any useful info, so
better to keep them hidden still.
Co-developed-by: Marcin Maka <marcin.maka@linux.intel.com>
Co-developed-by: Kevin Putnam <kevin.putnam@intel.com>
> doc: do not hide doxygen group documention

- developer_guides/debugability/ri-info/output_full_bytes.txt
- developer_guides/debugability/ri-info/output_headers.txt
- developer_guides/debugability/ri-info/output_verbose.txt
Update example output with content produced by the latest
version of sof-ri-info.
Format of module info was changed significantly and outdated
examples may confuse a reader.
> debugability: sof-ri-info: update examples

- conf.py
- contribute/contribute_guidelines.rst
- contribute/process/abiprocess.rst
- contribute/process/docbuild.rst
- getting_started/build-guide/build-from-scratch.rst
Rename `git-sof-[docs-]master` aliases to `-mainline`
Unhardcode two links.
See commit messages.
> Unhardcode -master aliases and two https: links

- developer_guides/fuzzer/fuzzing.rst
- developer_guides/linux_driver/architecture/sof_driver_arch.rst
- getting_started/build-guide/build-from-scratch.rst
- getting_started/build-guide/build-with-docker.rst
- introduction/index.rst
Switch internal links to `:ref:` per https://thesofproject.github.io/latest/contribute/doc_guidelines.html#internal-cross-reference-linking
`:ref:` internal links support offline work and don't die silently when someone changes a section name.
Fixes 37a14b1e352a, b270e65e19e15 and 2d4a0600fb9db
> Switch internal links to :ref: 

- Makefile
The default and recommended location for the doxygen build is a source
directory, which gets polluted by the build and incredibly tedious
to (dist)clean manually. Don't change that default and documentation
yet (baby steps) but make it at least possible to build (and clean)
doxygen outside the source directory per the usual CMake practices.
As a side-effect this makes the connection with doxygen and breathe less
implicit in the Makefile.
> Makefile: new SOF_DOC_BUILD un-hardcodes ../sof/doc

- developer_guides/index.rst
- developer_guides/testbench_fuzzing/testbench_afl_fuzzing.rst
This new section in the developer guide gives instructions on how
to build AFL fuzzer, use AFL provided wrapped gcc compiler to
build testbench for instrumenting it. It ends with an example of
fuzzing the volume component of the testbench with the AFL fuzzer
and the testbench.
Signed-off-by: Mohana Datta Yelugoti <ymdatta.work@gmail.com>
> developer_guides: Add instructions to run testbench with AFL fuzzer

- developer_guides/debugability/logger/index.rst
-v option is enabled by default, so there is another one to disable
this feauture.
Related with https://github.com/thesofproject/sof/pull/3326
> logger: Replace -v option with -n

- contribute/process/abiprocess.rst
Add a new section and guidance on how new and/or modified ABI
fields and enumerations must be documented in the header files.
> contribute: Add section on ABI change field annotation

- developer_guides/debugability/logger/index.rst
Each mechanism in logger tool chould be described in sof-dox.
Reference changes from https://github.com/thesofproject/sof/pull/2965
> logger: Describe runtime logger trace filtration usage

- getting_started/build-guide/build-with-docker.rst
The docker-build scripts bake the builder's Intel-internal proxy settings into the docker image. If someone wants to build outside Intel, the easiest way to do so is to clone all the sources outside the container first.
> Add "--recurse-submodules" to git clone in build-with-docker

- developer_guides/firmware/components/component-overview.rst
- developer_guides/firmware/components/images/comp-dev-states.pu
Fixes #290 
Add COMP_STATE_INIT to the diagram.
> developer guides: update components diagram

- .travis.yml
- conf.py
More aligned with users.
Should make no difference to the officially supported and entirely
hardcoded pip3 configuration. Will help prepare any future sphinx
upgrade.
> travis: upgrade Ubuntu from LTS 18.04 to LTS 20.04 

- conf.py
- developer_guides/linux_driver/architecture/sof_driver_arch.rst
- getting_started/build-guide/build-from-scratch.rst
Due to the lack of these links, the very first time I read this section
I assumed there was no other "kernel HOWTO" than this section elsewhere
in sof-docs and I did not search for anything else. So I did obviously
not find the pages linked to by this commit and I tried to figure
everything on my own instead which probably caused my biggest waste of
time when starting to work on SOF. No exaggeration.
I'm not sure why the ktest section is placed under "Setting up SOF on
hardware", maybe a different location for it would have helped me
too. Anyway adding a couple links is much easier than moving sections
around and a getting started guide is a good place for links to more
advanced documentation in any case. This getting started guide has
surprisingly few such links to more advanced topics. …
> getting_started: add vital kernel links

- developer_guides/linux_driver/architecture/sof_driver_arch.rst
- getting_started/build-guide/build-from-scratch.rst
> Corrected broken link for kconfig README doc.

- platforms/intel-cavs/commons/multicore-processing.rst
Synchronized with firmware version:
256c9343: ("smp: make MAX_CORE_COUNT an automatic Kconfig parameter")
> intel: cavs: Update multicore dox after MAX_CORE_COUNT removing

- developer_guides/topology/topology.rst
- platforms/intel-cavs/commons/multicore-processing.rst
Add guide and example to explain how to specify DSP core index for
pipeline or widgets/components.
Signed-off-by: Keyon Jie <yang.jie@linux.intel.com>
> topology: add guide for specify DSP cores

- getting_started/setup/setup_ktest_environment.rst
Under current ktest, user needs to clean up old kernel modules manually.
Signed-off-by: Fred Oh <fred.oh@linux.intel.com>
> ktest: add cleaning up old kernel modules

- getting_started/build-guide/build-from-scratch.rst
Add info how the set environment variable for using external key in signing.
Signed-off-by: Jaska Uimonen <jaska.uimonen@intel.com>
> build-guide: Add note for using external key in signing

- getting_started/build-guide/build-with-zephyr.rst
- getting_started/index.rst
SOF can be built as a Zephyr application. This document describes the process.
> Add documentation for building and running SOF under Zephyr

- .github/workflows/pull-request.yml
"deploy" steps not converted yet. I have never seen them run, are they
still in use?
Either way this first and most important part can be merged already.
> Convert .travis.yml to github actions

- .wokeignore
- rules-woke.yaml
Includes two files:
.wokeignore lists files to ignore when running Woke.
rules-woke.yaml is the customized file that must be run to accurately identify and correct non-inclusive terms.
This file is called by woke -c ./rules-woke.yaml
> Addition of files used to run Woke word checker.

- getting_started/build-guide/build-with-zephyr.rst
Update installation instructions under Zephyr to clarify post-installation verification and new rimage procedures.
> zephyr: update installation instructions

- .github/workflows/pull-request.yml
See comments and reference in the file.
> .github: apt-get update to work around github's broken package index

- getting_started/build-guide/build-from-scratch.rst
Use SOF_WORKSPACE consistently throughout the page to make it easier to
follow the instruction if the SOF_WORKSPACE != ~/work/sof
Signed-off-by: Peter Ujfalusi <peter.ujfalusi@gmail.com>
> build-guide: build-from-scratch: Use SOF_WORKSPACE throughout the page

- getting_started/build-guide/build-with-zephyr.rst
Zephyr, west, and rimage do not need to be italicized. 
Created numbered steps for both sections.
Tried to make this doc look more like Zephyr's documentation in terms of style.
> Grammatical edits to Build SOF with Zephyr

- architectures/dsp/intel/cavs-boot/cavs-dsp-boot-overview.rst
> Removed reference to "master" in cavs-dsp-boot-overview doc

- getting_started/build-guide/build-from-scratch.rst
- substitutions.txt
crosstool-ng fails to build with the gcc8.1-gdb8.1 configs and while there update the page for Tiger Lake as well.
> switch the build guide to gcc10.2-gdb9 (which works) and add Tiger Lake information

- conf.py
add_stylesheet is removed with sphinx 4.0 and this will cause error in
conf.py
Fix it by trying to use the new add_css_file introduced in 1.8 and fall
back to add_stylesheet for older sphinx version.
> conf.py: Add support for sphinx 4.0+

- getting_started/build-guide/build-with-zephyr.rst
rimage is downloaded automatically.
logtool.py is (slowly) being replaced.
> zephyr: simplify instructions thanks to new xtensa-build-zephyr.sh

- developer_guides/debugability/logger/index.rst
- getting_started/intel_debug/suggestions.rst
Add clarifications and details for debugging SOF issues.
The updates are created based on issue #347 in hope that the information in the documentation will be more user friendly.
> Update some debugging information

- getting_started/build-guide/build-from-scratch.rst
Developers must have the build-essential installed. It is highly unlikely
that a developer does not have it already, but for the sake of completeness
add a note about it.
> build-guide: Add instructions about ubuntu's build-essential metapackage

- getting_started/build-guide/build-from-scratch.rst
There is no mention in the documentation about "ct-install", the ct-ng is
installed in previous steps to $(pwd).
Fixes: a31ee37bae5f2 ("Toolchains and getting started guide: remove duplication, other fixes")
> build-guide: Correct ct-ng path for building all toolchains

- getting_started/build-guide/build-from-scratch.rst
We can not document every dependencies for all distributions, we already
lagging behind with some newer Ubuntu variants.
Add a generic note about this fact in the documentation for the users to be
aware of.
> build-guide: Add instruction on the possibility of missing packages

- developer_guides/firmware/cmake.rst
- developer_guides/unit_tests.rst
Explain how to "steal" parameters from scripts/xtensa-build-all.sh
Explain how to compile natively.
Link the two sections with each other.
`make platform_defconfig` was obsolete, replace with -DINIT_CONFIG
> Fix unit tests documentation

- developer_guides/unit_tests.rst
... and now even CI does it since
https://github.com/thesofproject/sof/pull/4543
Also mention run-cmocks.sh
> Unit tests: running them on the host _is_ possible.

- platforms/index.rst
This pull request adds the AMD Renoir platform specific information to the table.
Included clock, memory and audio controller instances related information to the table.
> Platforms: Add AMD platform specific information to the table

- platforms/index.rst
Add mt8195 mediatek platform information to the table.
Included clock, memory and audio controller instances to the table
Signed-off-by: YC Hung <yc.hung@mediatek.com>
Signed-off-by: Allen-KH Cheng <allen-kh.cheng@mediatek.com>
> Add mt8195 mediatek platform information to the table.

- contribute/process/docbuild.rst
cmake and ninja-build are required to run documentation processors, but these tools were not mentioned in the "Install documentation tools" section.
> Add cmake and ninja-build to the installation instructions

- getting_started/setup/setup_ktest_environment.rst
> ktest: add Fedora / grubby instructions

- developer_guides/debugability/logger/index.rst
If sof-logger is started (or restarted) while DSP is running,
the initial traces may come in incorrect order or are incomplete.
This is important to note when parsing the logger results.
BugLink: https://github.com/thesofproject/sof-test/issues/297
> debugability: logger: add note on DMA trace limitations

- getting_started/intel_debug/introduction.rst
Add list of options to develop on Chromebooks and links - especially
Zephyr's detailed Crouton guide.
> intel platforms: add list of Chromebook dev. environments

- getting_started/build-guide/build-from-scratch.rst
Do not mess with the host systemd or udev conf if making a local
installation to a home directory.
Signed-off-by: Jyri Sarha <jyri.mikko.oskari.sarha@intel.com>
> build-from-scratch: Minor fix to local alsa-utils install command

- developer_guides/debugability/coredump-reader/index.rst
Add documentation and practical example how to extract the DSP
coredump via Linux SOF driver debugfs interface and how to
parse the result with coredump-reader.
> developer_guides: add coredump-reader example usage on Linux

- developer_guides/unit_tests.rst
Also regroup -DTOOLCHAIN=xt closer to the other flags, stop hiding it
after the example.
> unit_tests: add workaround for uintptr_t redefinition

- getting_started/setup/setup_ktest_environment.rst
Reduce the number of remotes and use a script to create .config
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
> ktest: update needed git remotes and kconfig setups

- platforms/index.rst
Platform clock frequency information is required to get correct timestamps in sof-logger.
> Supported Platforms: Platform Clock column added

- conf.py
With a recent enough sphinx-build --version, this fixes the gazillion of
warnings recently added:
```
/home/runner/work/sof-docs/sof-docs/api/component-api.rst:21: WARNING: Error when parsing function declaration.
If the function has no return type:
Error in declarator or parameters-and-qualifiers
Invalid C++ declaration: Expected identifier in nested name, got keyword: void [error at 18]
static inline void comp_underrun (struct comp_dev *dev, struct comp_buffer __sparse_cache *source, uint32_t copy_bytes)
------------------^
If the function has a return type:
Error in declarator or parameters-and-qualifiers
If pointer to member declarator:
Invalid C++ declaration: Expected '::' in pointer to member (function). [error at 33]
static inline void comp_underrun (struct comp_dev *dev, struct …
```
> conf.py: cpp_id_attributes = ["__sparse_cache"]

- getting_started/build-guide/build-with-zephyr.rst
Add missing `git submodule update` as reported by @plbossart (thx!)
Also make the documentation ready for `xtensa-build-zephyr.py`
which... does not have any hack to automatically download git submodules
like the older .sh script has.
As a side-effect, this breaks down the process and adds an intermediate
`west build` step which removes one layer of indirection in case of some
Zephyr environment issue.
Cannot fully switch to the Python version yet because of bugs like
https://github.com/thesofproject/sof/pull/5906 but do recommend users to
start trying it.
> build-with-zephyr: fix submodules, get ready for new python script

- getting_started/intel_debug/suggestions.rst
Instead of repeating the same things on GitHub issues, maybe this
documentation will help.
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
> intel_debug: add suggestions for DMIC and ES8336 platforms

- developer_guides/testbench/build_testbench.rst
I've found Valgrind and bc are necessary to run the testbench. Neither
are listed in the general dependency list for Ubuntu 20.04 and only
Valgrind is listed for other versions.
Signed-off-by: Noah Klayman <noah.klayman@intel.com>
> testbench: add note to install runtime deps

- getting_started/build-guide/build-with-zephyr.rst
Introduction of west tool to SOF project in PR https://github.com/thesofproject/sof/pull/6005 required to update
build guide on how to use python convenience script and west tool.
Signed-off-by: Andrey Borisovich <andrey.borisovich@intel.com>
> getting_started/build-guide: update Build SOF with zephyr

- contribute/doc_guidelines.rst
- developer_guides/topology/topology.rst
- getting_started/intel_debug/introduction.rst
- getting_started/intel_debug/suggestions.rst
- getting_started/setup_linux/setup_ktest_environment.rst
Fixes many warnings found by sphinx 1.8.5 and likely other versions.
Don't forget to "make clean" so see all warnings.
> Add missing code-block:: types

- Makefile
- conf.py
- scripts/requirements-lax.txt
Without instant builds there is no drive-by contributor submitting
quick fixes.
Also update requirements-lax.txt to request
sphinxcontrib.plantuml>=0.11,<0.25
- Version 0.11 is the first version that supports
plantuml_output_format=none which makes the build at least 15
times faster. https://pypi.org/project/sphinxcontrib-plantuml/0.11/
- 0.24 is the last version successfully tested with
PIP_IGNORE_INSTALLED=0 and Ubuntu 20.04 (see .github/worflows/)
> Finally document how to achieve instant builds

- .github/workflows/pull-request.yml
Unlike scripts/requirements.txt, the purpose of
scripts/requirements-lax.txt is to run the latest and greatest.
> .github: upgrade LAX environment to Ubuntu 22.04

- developer_guides/debugability/probes/index.rst
Validity of these updates depend on this pull request being accepted:
https://github.com/thesofproject/sof/pull/6364
> Probes update

- architectures/firmware/sof-zephyr/images/sof_lib.pu
- architectures/firmware/sof-zephyr/images/sof_lib_zephyr.pu
- architectures/firmware/sof-zephyr/index.rst
- architectures/firmware/sof-zephyr/zephyr_api_integration.rst
Documentation of a unified SOF lib interface for the upper code and implementation of the interfaces with both Zephyr and legacy SOF parts.
> arch: fw: doc sof lib with zephyr and legacy configuration

- getting_started/intel_debug/suggestions.rst
The current version is outdated, update it to align with what we use +p to +pmf for example.
> getting_started: intel_debug: Update the sof-dyndbg.conf example

- platforms/index.rst
Add mt8186 mediatek platform information to the table. Included clock, memory and audio controller instances to the table
> Supported Platforms: add mt8186 mediatek platform information

- platforms/index.rst
Add mt8188 mediatek platform information to the table. Included clock, memory and audio controller instances to the table
> Supported Platforms: add mt8188 mediatek platform information

- getting_started/setup_linux/install_locally.rst
The directory mentioned in install_locally doesn't match the one mentioned in prepare_build_environment.
This mr fixes this.
> Update install_locally to match the directory created in prepare_build_environment

- getting_started/intel_debug/suggestions.rst
Fixes broken "arecord -Dhw:0,6 -c4 -r48000 -sS32_LE -d 10 test.wav" to "arecord -Dhw:0,6 -c4 -r48000 -fS32_LE -d 10 test.wav"
Link: https://github.com/thesofproject/sof-docs/issues/467
> getting_started: Digital mic issue: Fix arecord options

- .github/workflows/pull-request.yml
- scripts/requirements-lax.txt
- scripts/requirements.txt
> Workaround for warning "'ImageDraw' object has no attribute 'textsize'" with pillow 10.0.0

- getting_started/intel_debug/introduction.rst
Add tables documenting the firmare and topology filenames and their
locations, as expected by Linux SOF driver.
Related to ongoing discussions in:
- https://github.com/thesofproject/linux/issues/4590
- https://github.com/thesofproject/sof/pull/8210
> intel_debug: add info for Intel firmware and tplg filenames

- getting_started/intel_debug/introduction.rst
SOF supports platforms from Tiger Lake with IPC4, update the docuementation accordingly.
Update the MTL/LNL topology path to follow a generic pattern and add a note about the need for a symlink for the old path to retain backwards compatibility with released kernels.
> intel_debug: introduction: Update for pathnames for IPC4 support

- getting_started/intel_debug/suggestions.rst
The documentation was wrong about getting the quirk default. I've fixed these details.
> Fixed suggestions about getting ES8336 quirk default.

- getting_started/intel_debug/introduction.rst
Restrict the sof-ace-tplg symlink need to Meteor Lake only and change the sentecne as suggested by @deb-intel
Replaces #482
> intel_debug: introduction: Update the note for Meteor Lake topology path

- getting_started/setup_linux/setup_ktest_environment.rst
The GRUB documentation used to say `GRUB_DISABLE_SUBMENU=y`, now it says `GRUB_DISABLE_SUBMENU=true`
Also, the corresponding code is unreliable copy/paste/diverge:
https://github.com/rhboot/grub2/commit/ee4bd79ef28e6fa4a6
This makes GRUB submenus error-prone. As a broken grub.cfg makes the system unbootable, "harden" the corresponding documentation.
> ktest setup: GRUB submenu fixes

- architectures/firmware/sof-zephyr/rtos_layer/io_drivers/i2s/i2s_driver.rst
This commit adds a description of using SSP devices in loopback mode
> rtos: io_drivers: add loopback mode description

- developer_guides/debugability/coredump-reader/index.rst
Add a note that these instructions are not valid for SOF on Zephyr and add link to relevant piece of Zephyr documentation.
> developer_guides: coredump-reader: Add NOTE for Zephyr

- platforms/index.rst
As this topic has been discussed in many pull requests and bugs, add documentation on which platforms are supported in SOF main and which are only supported in stable-vx.yy branches. Also add a note explainin how sof-bin releases are made, gathering binaries for for all platforms.
> platforms: add separate table for older platforms

- developer_guides/topology2/topology2.rst
Describe what are split topologies and how to create it.
> topology2: add split topologies description

- conf.py
- developer_guides/firmware/llext_modules.rst
This pull request addresses the build errors caused by Sphinx warnings and a missing label definition in the documentation. The following changes have been made:
1. **Update link to  for `intel_modular_firmware_paths`**:
- Updated the link from `intel_firmware_paths` to `intel_modular_firmware_paths` in `developer_guides/firmware/llext_modules.rst` to resolve the docs build error.
- Commit: dc0495a29f68fcdf5e88f97d83b400d0e49c4b41
2. **Remove deprecated `display_version` configuration**:
- Removed the `display_version` option from `html_theme_options` in `conf.py` as it was deprecated in `sphinx-rtd-theme` since v3.0.0.
- Commit: eec6e47c7c4b780bd8e1ac0624334c30785d867c
3. **Remove unused `html_theme_path` configuration**:
- Removed the unused `html_theme_path` configuration from …
> Fix pull-request.yml build errors by addressing Sphinx warnings and adding missing label definition
