thesofproject/sof-docs

- conf.py
- index.rst
- platforms/index.rst
- platforms/intel-cavs/apollolake/apl-memory.rst
- platforms/intel-cavs/apollolake/images/apl-memory.dot
- platforms/intel-cavs/apollolake/index.rst
- platforms/intel-cavs/cannonlake/cnl-config.rst
- platforms/intel-cavs/cannonlake/cnl-memory.rst
- platforms/intel-cavs/cannonlake/images/cnl-memory.dot
- platforms/intel-cavs/cannonlake/index.rst
- platforms/intel-cavs/images/cavs-platform-deps.pu
- platforms/intel-cavs/index.rst
- scripts/plantuml.cfg
> doc: initial subtree for supported platforms

- getting_started/cavs-boot/apollolake/apl-boot-ldr.rst
- getting_started/cavs-boot/apollolake/apl-boot-rom.rst
- getting_started/cavs-boot/apollolake/images/apl-rom-flow.pu
- getting_started/cavs-boot/apollolake/index.rst
- getting_started/cavs-boot/cavs-dsp-boot-overview.rst
- getting_started/cavs-boot/images/boot-dsp.pu
- getting_started/cavs-boot/images/boot-ldr-flow.pu
- getting_started/cavs-boot/images/loading-bins.pu
- getting_started/cavs-boot/images/write-bin.pu
- getting_started/cavs-boot/index.rst
- getting_started/index.rst
> doc: cavs platforms boot flow documented.

- contribute/dox-source-code.rst
- contribute/index.rst
> doc: added quick guide for source code dox

- developer_guides/index.rst
- developer_guides/unit_tests.rst
> Cmocka unit tests rst

- conf.py
> doc: changed output format of uml diagrams to svg

- getting_started/build-guide/build-from-scratch.rst
- getting_started/build-guide/build-with-docker.rst
- getting_started/index.rst
- substitutions.txt
Include some platform names and build guide support.
> build guide support

- developer_guides/drivers/dai/index.rst
- developer_guides/drivers/dma/index.rst
- developer_guides/drivers/index.rst
- developer_guides/unit_tests.rst
Please DO NOT merge this commit until it has been reviewed by all reviewers.
> update dev guide files

- howtos/tech/compile_wsl.rst
- howtos/tech/placeholder.rst
> howto: sof compilation with wsl

- howtos/tech/compile_wsl.rst
> edits to build win 10 on WSL

- howtos/tech/compile_wsl.rst
> Corrected spacing issue compile_wsl

- platforms/intel-cavs/icelake/index.rst
- platforms/intel-cavs/images/cavs-platform-deps.pu
- platforms/intel-cavs/index.rst
> doc: platforms: icelake added to the cavs list

- developer_guides/kernel/work-queue.rst
- platforms/intel-cavs/commons/work-queue.rst
> Minor edits to work queue files

- developer_guides/kernel/images/memory-zones.dot
- developer_guides/kernel/images/runtime-zone.dot
- developer_guides/kernel/images/system-zone.dot
- developer_guides/kernel/index.rst
- developer_guides/kernel/mem-mgmt.rst
> doc: memory management, part one

- developer_guides/apps/components/component-api.rst
- developer_guides/apps/components/component-mgmt-api.rst
- developer_guides/apps/components/images/comp-dev-states.pu
- developer_guides/apps/components/images/comp-driver.pu
- developer_guides/apps/components/images/comp-new-flow.pu
- developer_guides/apps/components/images/comp-ops-copy.pu
- developer_guides/apps/components/images/comp-ops-dai-config.pu
- developer_guides/apps/components/images/comp-ops-free.pu
- developer_guides/apps/components/images/comp-ops.pu
- developer_guides/apps/components/images/component-mgmt-api.pu
- developer_guides/apps/components/index.rst
- developer_guides/apps/components/new-comp-guide.rst
- developer_guides/apps/index.rst
- developer_guides/apps/pipelines/images/ppl-new.pu
- developer_guides/apps/pipelines/images/ppl-op-downstream.pu
- developer_guides/apps/pipelines/images/ppl-operations.pu
- developer_guides/apps/pipelines/images/ppl-params.pu
- developer_guides/apps/pipelines/images/ppl-reset.pu
- developer_guides/apps/pipelines/images/ppl-struct.pu
- developer_guides/apps/pipelines/images/ppl-task.pu
- developer_guides/apps/pipelines/index.rst
- developer_guides/index.rst
> doc: pipelines, basic flows documented

- architectures/host/index.rst
- architectures/index.rst
- architectures/xtensa-dsp/index.rst
- architectures/xtensa-dsp/smp/images/idc-send-message.pu
- architectures/xtensa-dsp/smp/index.rst
- architectures/xtensa-dsp/up/index.rst
- index.rst
- platforms/intel-cavs/commons/images/core-enable.pu
- platforms/intel-cavs/commons/index.rst
- platforms/intel-cavs/commons/multicore-processing.rst
Adds documentation on SMP architecture and multicore processing.
Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>
> smp: add docs regarding multiple cores handling

- developer_guides/apps/components/component-api.rst
- developer_guides/apps/pipelines/index.rst
- developer_guides/kernel/mem-mgmt.rst
> Grammatical edits to PR #41 and #42

- getting_started/build-guide/build-from-scratch.rst
> build-guide: Fix typo in make command

- release_notes.rst
> Completed v1.2 SOF Release Notes

- getting_started/build-guide/build-from-scratch.rst
> build: from scratch: fix whitespace

- howtos/process/docbuild.rst
Installation process update documents steps to run document
processors in Python3 virtualized environment. Steps tested on
Ubuntu 18.04
> howtos: process: Installation troubleshooting

- howtos/process/docbuild.rst
> Edit Installation troubleshooting

- getting_started/setup/setup_up_2_board.rst
all minor fixes but very necessary changes for UP2 board
> Fix typos and add more clarification for blacklist-dsp.conf

- getting_started/build-guide/build-from-scratch.rst
- getting_started/build-guide/build-with-docker.rst
Update build doc to remove all soft related stuff and update build command and build script guide.
Fix #67
> Update build doc for the soft => sof/tools change

- getting_started/build-guide/build-from-scratch.rst
Should be merged after https://github.com/thesofproject/sof/pull/845
> build: update for cmake

- developer_guides/unit_tests.rst
Should be merged after https://github.com/thesofproject/sof/pull/845
> unit tests: update for cmake

- getting_started/build-guide/build-from-scratch.rst
> build: fix relative path

- getting_started/setup/setup_up_2_board.rst
Signed-off-by: Kelly Ledford <kelly.ledford@intel.com>
> setup: up2: Fix error in entering BIOS instruction

- developer_guides/cmake.rst
- developer_guides/index.rst
CMake is mainstream tool, so for now I just describe things specific to our project (Arguments). Later I may add more howtos/best practices in this section.
> cmake: arguments

- getting_started/build-guide/build-with-docker.rst
Use organization instead of personal account.
Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>
> build: update docker repo into organization

- developer_guides/debugability/logger/index.rst
- getting_started/build-guide/build-from-scratch.rst
- getting_started/build-guide/build-with-docker.rst
- getting_started/effects/how-to-use-sof-eqctl-tool.rst
- getting_started/setup/setup_ktest_environment.rst
- getting_started/setup/setup_minnowboard_turbot.rst
- getting_started/setup/setup_up_2_board.rst
- release_notes.rst
Addresses #86 -- prompt removal from code examples.
Other requests are addressed in PR #93
> Remove prompt code examples

- getting_started/build-guide/build-from-scratch.rst
Addresses changes & requests in #86 and #87 other than removing the prompt from the code examples (= PR #92)
> Getting Started: update instructions + fix minor misspellings

- getting_started/setup/setup_minnowboard_turbot.rst
Signed-off-by: Mattijs Korpershoek <mattijsx.korpershoek@intel.com>
> getting_started: fix typo: s/Brossart/Bossart

- developer_guides/cmake.rst
Updated for new argument + Added some sections descriptions
> cmake: add openssl path argument

- getting_started/build-guide/build-from-scratch.rst
> build: tools: cmake commands update

- developer_guides/cmake.rst
- howtos/tech/build-cmocka.rst
> howto: build cmocka for xtensa

- developer_guides/debugability/coredump-reader/index.rst
- developer_guides/debugability/index.rst
Signed-off-by: Adrian Bonislawski <adrian.bonislawski@linux.intel.com>
> debugability: coredump usage page

- getting_started/setup/setup_up_2_board.rst
Signed-off-by: Kelly Ledford <kelly.ledford@intel.com>
> Update BIOS to public v4.0 link

- developer_guides/apps/index.rst
- developer_guides/apps/kd_integration/images/kd-component-diagram.pu
- developer_guides/apps/kd_integration/images/kd-e2e-sequence-diagram.pu
- developer_guides/apps/kd_integration/images/kd-timing-diagram.pu
- developer_guides/apps/kd_integration/index.rst
- developer_guides/apps/kd_integration/kd-integration.rst
The Keyword Detection algorithm requires dedicated cross-domain support  that spans between SW & FW. The PR covers arch documentation for intro, E2E flows, FW topology and FW components functional scope to support  integration of a custom keyword detection algorithm. The SW/FW infrastructure support includes buffering of a data used for keyword  detection in FW and a succeeding  command for an additional processing on host CPU.
Power flows & scheduling considerations will be described separately.
> Add E2E flows and FW architecture for Keyword Detection (KD) use case

- developer_guides/apps/kd_integration/kd-integration.rst
Please review to make sure I didn't impact meaning.
Signed-off-by: Kevin Putnam <kevin.putnam@intel.com>
> Made some changes to improve readability

- getting_started/build-guide/build-from-scratch.rst
I've overlooked that one before.
> Fixed cht build firmware cmake arguments

- api/component-api.rst
- api/index.rst
> api: link to component api dox added

- getting_started/build-guide/build-from-scratch.rst
- getting_started/setup/setup_ktest_environment.rst
- getting_started/setup/setup_up_2_board.rst
- platforms/index.rst
- platforms/intel-cavs/apollolake/index.rst
- platforms/intel-cavs/index.rst
- platforms/intel-legacy/baytrail/index.rst
- platforms/intel-legacy/broadwell/index.rst
- platforms/intel-legacy/index.rst
- platforms/intel-legacy/merrifield/index.rst
updated links for kconfigs and added info on supported platforms (included legacy)
> Minor doc updates

- substitutions.txt
Substitution for Ice Lake added.
> Adding substitution for Ice Lake platfrom.

- developer_guides/firmware/component-tutorial/tut-i-basic-fw-code.rst
- developer_guides/firmware/component-tutorial/tut-ii-topology.rst
- developer_guides/firmware/component-tutorial/tut-iii-runtime-params.rst
- developer_guides/firmware/component-tutorial/tut-intro.rst
- developer_guides/firmware/component-tutorial/tut-iv-exceptions.rst
- developer_guides/firmware/components/component-overview.rst
- developer_guides/firmware/components/index.rst
- developer_guides/firmware/hello_world.rst
- developer_guides/firmware/index.rst
A step by step approach to creating a new audio component and adding it to a simple audio pipeline.
> Firmware: new component tutorial

- developer_guides/firmware/component-tutorial/tut-i-basic-fw-code.rst
- developer_guides/firmware/component-tutorial/tut-ii-topology.rst
- developer_guides/firmware/component-tutorial/tut-iii-runtime-params.rst
- developer_guides/firmware/component-tutorial/tut-intro.rst
- developer_guides/firmware/component-tutorial/tut-iv-exceptions.rst
> Grammatical edits for component-tutorial docs.

- getting_started/build-guide/build-3rd-party-toolchain.rst
> Grammatical edits.

- getting_started/build-guide/build-3rd-party-toolchain.rst
- getting_started/index.rst
The getting started guide section related to building with third party tools
updated.  The order of the chapters in build-guide manually enforced.
> Modify title of a 3P toolchain support section

- developer_guides/firmware/component-tutorial/tut-ii-topology.rst
> coponent: fix topology max control size in tutorial

- getting_started/build-guide/build-from-scratch.rst
Signed-off-by: Kelly Ledford <kelly.ledford@intel.com>
> Correct line spacing and minor count update

- README.md
> README: fix doc build link

- developer_guides/firmware/component-tutorial/tut-i-basic-fw-code.rst
- developer_guides/firmware/component-tutorial/tut-ii-topology.rst
The amp component from the documentation will currently not work as-is. Some patching is needed to get it in sync with the latest changes ...
> Firmware Hello World amp component tutorial updates

- contribute/process/docbuild.rst
Signed-off-by: Michal Wasko <michal.wasko@intel.com>
> Windows sof-docs build environment troubleshooting

- getting_started/build-guide/build-from-scratch.rst
Initial support to build firmware for i.MX8M platform.
> getting_started: Add build documenation for i.MX8M

- algos/index.rst
- index.rst
Still to be completed.
@singalsu this one is for you. We need to create some introductory information for the free processing
components. 
Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
> [WIP] algorithms: Add section on free algorithms.

- algos/index.rst
> Edited Agorithm Spec Info section in algos/index

- platforms/index.rst
> Minor updates to Supported Platforms doc

- platforms/index.rst
> Additional update to Supported Platforms doc

- getting_started/build-guide/build-from-scratch.rst
> Grammar updates to Build from scratch doc

- getting_started/build-guide/build-from-scratch.rst
> Corrected word wrap in Build from Scratch doc

- developer_guides/virtualization/virtualization.rst
> Corrected word-wrap in SOF VirtIO Design doc

- algos/index.rst
This patch updates the component list in the table to match
current SOF git master version adds more verbose descriptions.
Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>
> Algorithms: Update processing summary table

- platforms/index.rst
First platform from i.MX8M family is i.MX8MP. The i.MX 8M Plus
family focuses on machine learning and vision, advanced multimedia,
and industrial IoT with high reliability.
More info at:
https://www.nxp.com/products/processors-and-microcontrollers/arm-processors/i.mx-applications-processors/i.mx-8-processors/i.mx-8m-plus-arm-cortex-a53-machine-learning-vision-multimedia-and-industrial-iot:IMX8MPLUS
> platforms: Add entry for i.MX8M

- algos/index.rst
> Grammatical edits to Algorithms doc

- algos/index.rst
Add informtation about planned components:
* Crossover Filter
* Dynamic Range Compressor
* DC Blocker
Signed-off-by: Curtis Malainey <cujomalainey@chromium.org>
> Algorithms: Add description for Crossover, DCB and DRC components

- algos/index.rst
> Small edits to algos/index.html

- platforms/intel-cavs/index.rst
- platforms/intel-cavs/tigerlake/index.rst
- platforms/intel-cavs/tigerlake/tgl-memory.rst
> Smile grammatical edits to Tiger Lake pages

- platforms/intel-cavs/cannonlake/cnl-memory.rst
- platforms/intel-cavs/tigerlake/tgl-memory.rst
> Minor grammatical updates to tgl/cnl memory docs

- architectures/host/index.rst
> Added link to detailed SOF Driver Arch doc from main Arch page

- developer_guides/introduction.rst
> More grammatical updates to Dev-Guide Intro page

- contribute/index.rst
- contribute/linux/development_tree.rst
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
> contributing: add Linux development/integration flows

- contribute/linux/development_tree.rst
> Grammatical updates to Linux SOF drivers page

- algos/index.rst
- developer_guides/index.rst
- platforms/index.rst
> Tighten nav bar headings: platform, algorithms, dev guides

- developer_guides/virtualisation/files/q-v6.sh
- developer_guides/virtualisation/running.rst
This is a brief description of running SOF in a virtual machine.
To be extended and improved as respective repositories merge VirtIO code.
> VirtIO: add running instructions

- developer_guides/virtualization/files/q-v6.sh
Remove commented out code and add an explanatory comment to the QEMU
launch script.
> virtualization: clean up QEMU script

- developer_guides/firmware/kd_integration/kd-integration.rst
- developer_guides/virtualization/files/q-v6.sh
- developer_guides/virtualization/running.rst
- developer_guides/virtualization/virtualization.rst
Edited comments in q-v6.sh
Minor grammatical updates in running.rst and virtualization.rst
Grammatical updates to kd-integration.rst
> Updates to various virtualization and integration files

- developer_guides/firmware/components/component-overview.rst
> Grammatical updates to components-overview.rst

- developer_guides/firmware/components/component-overview.rst
> Minor edits to component-overview.rst

- developer_guides/debugability/index.rst
- developer_guides/debugability/probes/index.rst
Simple getting started with probes
Signed-off-by: Adrian Bonislawski <adrian.bonislawski@linux.intel.com>
> probes: add probes documentation

- developer_guides/debugability/probes/index.rst
> Minor grammatical edits to /probes/index.rst

- api/component-api.rst
> Minor edits to component-api.rst

- algos/demux/demux.rst
- algos/index.rst
> Edits to demux page; added toctree info to algos/index

- .travis.yml
- Makefile
- conf.py
- contribute/process/docbuild.rst
> Much faster build + increase sphinx-build verbosity

- .gitignore
- setup.py
> Correcting author errors

- developer_guides/firmware/component-tutorial/tut-i-basic-fw-code.rst
> Minor edits to fw code tutorial

- contribute/process/docbuild.rst
- scripts/requirements-lax.txt
> Minor grammatical updates to build docs

- .travis.yml
See commit messages here and previous, already merged and heavily commented e987dcf322cb for details.
Also upgrade Ubuntu to 18.04 since is two years old now (20.04 is almost released)
This doesn't make much difference anyway since 'language: python' runs everything in a virtualenv.
> Travis: add new job for scripts/requirements-lax.txt

- developer_guides/debugability/index.rst
- developer_guides/debugability/ri-info/index.rst
- developer_guides/debugability/ri-info/output_full_bytes.txt
- developer_guides/debugability/ri-info/output_headers.txt
- developer_guides/debugability/ri-info/output_verbose.txt
This tool is part of sof repository and should be described in sof-docs
> Debugability: Add sof-ri-info description

- developer_guides/debugability/ri-info/index.rst
> Minor grammatical edits to ri-info/index page

- developer_guides/firmware/component-tutorial/tut-i-basic-fw-code.rst
- developer_guides/firmware/component-tutorial/tut-ii-topology.rst
- developer_guides/firmware/component-tutorial/tut-iii-runtime-params.rst
Part I is aligned with the recent changes to trace context. Other parts are aligned with the current version of topology definition.
> Update new component tutorial

- developer_guides/index.rst
- developer_guides/rimage/extended_manifest.rst
- developer_guides/rimage/images/ext_man_build_flow.pu
- developer_guides/rimage/images/image_build_flow.pu
- developer_guides/rimage/index.rst
Add rimage and ext_manifest description
> Rimage and extended manifest description

- developer_guides/rimage/extended_manifest.rst
- developer_guides/rimage/index.rst
> Grammatical edits to rimage files

- conf.py
> Update SOF Copyright 2020.

- developer_guides/linux_driver/third_party/keyword_detect/keyword_detect.rst
> Grammatical edits to Keyword Detection page

- developer_guides/fuzzer/fuzzing.rst
- developer_guides/index.rst
This new section in developer guides gives instructions on how to
get started with fuzzing in docker containers using sof image.
Signed-off-by: Mohana Datta Yelugoti <ymdatta.work@gmail.com>
> developer_guides: Add instructions on fuzzing in docker containers

- release.rst
> Updates to release page

- developer_guides/firmware/components/component-overview.rst
- developer_guides/uuid/index.rst
> Grammatical edits to UUID documentation.

- developer_guides/fuzzer/fuzzing.rst
> Grammatical edits to fuzzing docker page

- contribute/linux/development_tree.rst
- contribute/process/abiprocess.rst
> Grammatical edits for ABI process docs

- developer_guides/firmware/mem-mgmt.rst
Describes shared data concept and possible ways of implementation.
Signed-off-by: Tomasz Lauda <tomasz.lauda@linux.intel.com>
> memory: add section about shared data

- developer_guides/firmware/mem-mgmt.rst
> Grammatical edits to the memory management page.

- architectures/dsp/intel/cavs-boot/cavs-dsp-boot-overview.rst
- architectures/dsp/intel/smp/index.rst
- developer_guides/linux_driver/architecture/sof_driver_arch.rst
- developer_guides/topology/topology.rst
- platforms/intel-cavs/commons/work-queue.rst
> Removed references to master/slave; replaced with primary/secondary

- developer_guides/firmware/mem-mgmt.rst
> Replace "master" with "primary" in Mem Mangt doc

- developer_guides/linux_driver/architecture/sof_driver_arch.rst
- developer_guides/topology/topology.rst
> Changed "master" in Topology and SOF Arch docs

- developer_guides/firmware/schedulers.rst
> Grammatical edits to the schedulers doc

- developer_guides/debugability/probes/index.rst
Add few more necessary details to enable first time user
for effective use of the probes debug capability.
Signed-off-by: Yong Zhi <yong.zhi@intel.com>
> probes: Add more details on how to use the feature

- developer_guides/debugability/probes/index.rst
> Grammatical edits to Probes doc

- developer_guides/index.rst
- developer_guides/xtrun/index.rst
Add instructions for using xt-run in standalone binaries
and in unit testing framework.
> developer guides: using xt-run

- developer_guides/xtrun/index.rst
> Edits to xt-run doc

- introduction/index.rst
> Added Xtensa FAQs to the SOF intro page. Also, edited page for clarity.

- contribute/process/abiprocess.rst
> Minor grammatical edits to abiprocess.html

- contribute/process/abiprocess.rst
> One additional edit to abiprocess.html

- developer_guides/testbench/build_testbench.rst
- developer_guides/testbench/debug_in_testbench.rst
- developer_guides/testbench/index.rst
- developer_guides/testbench/prepare_new_component.rst
- developer_guides/testbench/test_audio_quality.rst
> Grammatical edits to testbench docs

- developer_guides/debugability/logger/index.rst
> Grammatical edits to debugability/logger/index

- developer_guides/firmware/cmake.rst
Add some new CMake flags that are already in SOF but are not documented.
> cmake: flags FIRMWARE_NAME, MEU_NO_SIGN, MEU_OFFSET

- architectures/dsp/intel/smp/index.rst
- developer_guides/linux_driver/architecture/sof_driver_arch.rst
- developer_guides/topology/topology.rst
> Updated master-slave references

- getting_started/index.rst
- getting_started/intel_debug/introduction.rst
- getting_started/intel_debug/suggestions.rst
Rather than provide the same guidance over and over in GitHub issues,
write down a set of suggestions to help users/distros solve their
issues or report issues with more information.
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
> getting_started: add debug information for users/distros

- platforms/intel-cavs/commons/multicore-processing.rst
> Minor grammatical edits on multicore doc.

- getting_started/index.rst
- getting_started/intel_debug/introduction.rst
- getting_started/intel_debug/suggestions.rst
> Minor grammatical edits to debug docs

- developer_guides/debugability/logger/index.rst
Add few extra information about trace filtering system limitations.
> Logger filtering extra info

- developer_guides/debugability/logger/index.rst
> Made grammatical edits to logger page.

- algos/tdfb/time_domain_fixed_beamformer.rst
> Grammatical edits to TDFB doc

- developer_guides/topology/topology.rst
- platforms/intel-cavs/commons/multicore-processing.rst
> Minor edits to topology DSP and platforms docs

- getting_started/setup/setup_ktest_environment.rst
I found all `grub-reboot` guides either too long or too short or confusing
or all of the above :-)
> ktest: add grub-reboot cheat sheet

- release.rst
> Update release number and date.

- getting_started/setup/setup_ktest_environment.rst
Among other meaninglessness sins, 'test' is not SOF- or even audio-
specific and ungreppable. Don't change it the sample
configuration (yet?)  but at least give the option to change it.
This requires dropping the minus sign from '-test' example because
update-grub uses minus as a separator and ktest fails with:
Could not find ''Ubuntu, with Linux -test''
Also add some comments explaining why things work despite the hack where
/lib/modules/x.y.z-LOCALVERSION does not match /boot/vmlinuz-$LOCALVERSION
> ktest: un-hardcode $LOCALVERSION

- getting_started/build-guide/build-with-zephyr.rst
- getting_started/index.rst
> Grammatical edits to building SOF with Zephyr

- getting_started/intel_debug/introduction.rst
- getting_started/intel_debug/suggestions.rst
> Grammatical edits to ME debug info

- conf.py
> Updated copyright to 2021

- release.rst
This is not a show-stopper. Added simple PR to make sure my new laptop has correct git configurations.
> Updated release date for SOF 1.6.1

- .github/workflows/woke.yml
- .github/workflows/woke_pr.yml
Add PR woke checker with reviewdog
preview on https://github.com/xiulipan/sof-docs/pull/2 it will add review comments to GitHub from woke check.
Add manually trigger woke workflow
guide here https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
This will allow you to manually run woke check on existing branch with GitHub Action.
> Add woke test

- platforms/intel-cavs/commons/work-queue.rst
This is a simple cleanup. Also testing new build process.
> Remove old comments re: master/slave reference

- algos/demux/demux.rst
> Minor grammatical edits to demux.html

- architectures/dsp/index.rst
this is a big astraction
Signed-off-by: Curtis Malainey <cujomalainey@chromium.org>
> dsp: fix typo

- release.rst
> Update release page to reflect 1.7

- getting_started/build-guide/build-from-scratch.rst
Fix the CMake example, it has been broken since defconfig change
https://github.com/thesofproject/sof/pull/3821
Fix the default target when building tools.
Replace a lot of the massive copy/paste with "for platform" loops.
Move PATH changes to newlib section and explain that they don't need to
be permanent.
> Toolchains and getting started guide: remove duplication, other fixes

- getting_started/build-guide/build-from-scratch.rst
It's been one release since
https://github.com/thesofproject/sof/pull/3845 was merged.
> Add installer to getting started guide

- getting_started/build-guide/build-from-scratch.rst
> Grammatical edits to installing packaged dependencies

- getting_started/build-guide/build-from-scratch.rst
I have taken the time to install Ubuntu 20.04.2 to VBox.
Based on that I would suggest the following clarifications and fixes to the
build guide.
> build-guide: Updates based on a clean Ubuntu 20.04 installation

- conf.py
- getting_started/build-guide/build-from-scratch.rst
> Grammatical edits to build from scratch; small conf.py edit

- getting_started/index.rst
- getting_started/nxp/sof_imx_user_guide.rst
This is intended for newcomers, integrators or developers just
starting with i.MX platforms.
> [DRAFT] getting-started: Add SOF user guide for i.MX platforms

- getting_started/nxp/sof_imx_user_guide.rst
This adds more documentation for user guide.
> SOF on NXP i.MX8 userguide continuation

- getting_started/nxp/sof_imx_user_guide.rst
This describes how to use SRC and Audio compress features with i.MX8.
> getting-started: Add SRC and Audio compress for i.MX user guide

- getting_started/index.rst
- getting_started/nxp/sof_imx_user_guide.rst
Style updates made for SOF website consistency.
> Grammatical and style edits to NXP IMX page.

- CODEOWNERS
- release.rst
> Update to v1.9 release and add @anton-intel to codeowner page

- contribute/process/docbuild.rst
- platforms/index.rst
Copied the Tigerlake row and renamed it to Alderlake.
> Add Intel Alderlake to Supported Platforms

- getting_started/build-guide/build-from-scratch.rst
- getting_started/build-guide/build-with-docker.rst
Mostly stylistic changes that do not require tech review.
> Edit the topic so it looks like a task. Minor corrections to commands

- getting_started/intel_debug/introduction.rst
> Minor grammar and style changes

- getting_started/intel_debug/introduction.rst
A correction for the Portage build system description.
> Correction: intel_debug introductions

- getting_started/build-guide/build-with-docker.rst
Make the user choice between the Docker image build options clearer.
> Correction: Build SOF with Docker

- developer_guides/index.rst
- developer_guides/topology2/topology2.rst
Add usage documentation for topology 2.0.
Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>
> Add documentation for Topology 2.0

- conf.py
- release.rst
Please merge AFTER the SOF 2.0 release occurs.
> Change the release version to 2.0 for the SOF 2.0 release

- getting_started/build-guide/build-from-scratch.rst
- getting_started/setup/setup_ktest_environment.rst
Just a minor thing I bumped into while setting up and testing ktest environment.
> Minor ktest fix

- developer_guides/debugability/index.rst
- developer_guides/debugability/perf-counters/index.rst
Performance counters usage descriptions added
> debugability: performance counters

- release.rst
> Updated release page to 2.1.1

- conf.py
> Update conf.py to reflect 2.2 release

- getting_started/build-guide/build-from-scratch.rst
Signed-off-by: Noah Klayman <noah.klayman@intel.com>
Tested with a Fedora Docker container by going through this page and making sure everything builds successfully. Are there any other commands that should be run to verify these are all the necessary deps?
> getting_started/build-guide: add dep list for Fedora

- getting_started/build-guide/build-from-scratch.rst
5 commits, see commit messages
> Toolchains and getting started: minor fixes

- getting_started/build-guide/build-with-zephyr.rst
> Grammar and style updates to SOF-Zephyr file

- release.rst
> Add release 2.3 info

- architectures/firmware/sof-zephyr/rtos_layer/index.rst
- architectures/firmware/sof-zephyr/rtos_layer/io_drivers/dmic/dmic_driver.rst
- architectures/firmware/sof-zephyr/rtos_layer/io_drivers/dmic/images/dmic_diagram.pu
- architectures/firmware/sof-zephyr/rtos_layer/io_drivers/dmic/images/dmic_gateway_init.pu
- architectures/firmware/sof-zephyr/rtos_layer/io_drivers/dmic/images/dmic_gateway_release.pu
- architectures/firmware/sof-zephyr/rtos_layer/io_drivers/dmic/images/dmic_gateway_state_transitions.pu
- architectures/firmware/sof-zephyr/rtos_layer/io_drivers/hda/hda_driver.rst
- architectures/firmware/sof-zephyr/rtos_layer/io_drivers/hda/images/hda_capture.pu
- architectures/firmware/sof-zephyr/rtos_layer/io_drivers/hda/images/hda_io_driver_deps.pu
- architectures/firmware/sof-zephyr/rtos_layer/io_drivers/hda/images/hda_playback.pu
- architectures/firmware/sof-zephyr/rtos_layer/io_drivers/i2s/i2s_driver.rst
- architectures/firmware/sof-zephyr/rtos_layer/io_drivers/i2s/images/i2s_diagram.pu
- architectures/firmware/sof-zephyr/rtos_layer/io_drivers/i2s/images/i2s_tdm.dot
- architectures/firmware/sof-zephyr/rtos_layer/io_drivers/images/io_drivers_diagram.pu
- architectures/firmware/sof-zephyr/rtos_layer/io_drivers/index.rst
HDA, I2S and DMIC Zephyr IO Drivers integration with SOF. Architecture description and diagrams including Gateways concept.
> SOF - Zephyr IO drivers - FW Architecture

- architectures/firmware/sof-zephyr/mpp_layer/async_messaging.rst
- architectures/firmware/sof-zephyr/mpp_layer/images/async_messaging/flow_prod_cons_same_core.pu
- architectures/firmware/sof-zephyr/mpp_layer/images/async_messaging/flow_prod_primary_cons_secondary_core.pu
- architectures/firmware/sof-zephyr/mpp_layer/index.rst
- developer_guides/firmware/async_messaging_best_practices.rst
- developer_guides/firmware/index.rst
Asynchronous Messaging Service (AMS) description and flows.
Developers Guide - AMS Best Practices
> Asynchronous Messaging Service - FW Architecture

- CODEOWNERS
More people to receive a notification when a change to any file is being made.
> codeowners: add more people

- conf.py
- release.rst
- scripts/requirements.txt
> Update req.txt file, update copyright, change release number

- .github/workflows/pull-request.yml
- .github/workflows/woke.yml
- .github/workflows/woke_pr.yml
> Update deprecated actions

- architectures/firmware/sof-zephyr/rtos_layer/index.rst
- architectures/firmware/sof-zephyr/rtos_layer/memory_management/heap_sharing.rst
- architectures/firmware/sof-zephyr/rtos_layer/memory_management/images/dynamic_module_load.pu
- architectures/firmware/sof-zephyr/rtos_layer/memory_management/images/heaps.pu
- architectures/firmware/sof-zephyr/rtos_layer/memory_management/images/memory_allocation.pu
- architectures/firmware/sof-zephyr/rtos_layer/memory_management/images/memory_allocation_from_memory_driver.pu
- architectures/firmware/sof-zephyr/rtos_layer/memory_management/images/memory_initialization.pu
- architectures/firmware/sof-zephyr/rtos_layer/memory_management/images/memory_management_layers.pu
- architectures/firmware/sof-zephyr/rtos_layer/memory_management/index.rst
- architectures/firmware/sof-zephyr/rtos_layer/memory_management/memory_management_driver.rst
- architectures/firmware/sof-zephyr/rtos_layer/memory_management/memory_management_flows.rst
- architectures/firmware/sof-zephyr/rtos_layer/memory_management/memory_zones.rst
- architectures/firmware/sof-zephyr/rtos_layer/memory_management/mpp_memory_management.rst
Memory management description, design and flows based on Zephyr infrastructure
> Zephyr Memory Management FW Architecture

- contribute/process/docbuild.rst
- scripts/docker_build/Dockerfile
- scripts/docker_build/docker-build.sh
Docker image and build script added to support sof-docs documentation generation using Docker.
> Docker build support

- architectures/firmware/sof-common/components/component-module-api.rst
- architectures/firmware/sof-zephyr/app_layer/images/app_layer_diagram.pu
- architectures/firmware/sof-zephyr/app_layer/index.rst
- getting_started/index.rst
- getting_started/loadable_modules/lmdk_user_guide.rst
Add guide describing how loadable modules are build using LMDK (Loadable Modules Development Kit).
> Getting Started: introduce loadable modules

- developer_guides/debugability/logger/index.rst
plus some general restructuring
> sof-logger-doc: how to disable dsp suspension on imx8mp

- architectures/firmware/sof-zephyr/mpp_layer/images/mpp_scheduling/edf_scheduling.diag
- conf.py
- scripts/requirements.txt
> Add warnings to stop using blockdiag as it is orphaned

- developer_guides/debugability/index.rst
- developer_guides/debugability/shell/index.rst
Add basic introduction and usage documentation on how to use Zephyr shell feature with SOF.
> developer_guides: debugability: shell: add usage documentation

- conf.py
- release.rst
Necessary version updates for 2.10.0.
> update version info in conf.py and release file

- conf.py
- scripts/requirements-lax.txt
jQuery was not being loaded automatically. Force load it in extensions.
Fix for #494
> Fixes issue where search requests hang.

- conf.py
- release.rst
conf.py: version number update
release: version number and date update
> Update files to indicate new release
